<a href="https://colab.research.google.com/github/WizardOfCodes442/Numpy-docs/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

np.random.seed(0) #seed for reproductibility

x1 = np.random.randint(10, size=6) #One dimensional array
x2 = np.random.randint(10, size=(3,4)) #Two dimensional array
x3 = np.random.randint(10, size=(3,4, 5)) #Three-dimensional array

#Each array has attributes ndim( the number of dimensions), shape (the size of each dimension)
#and size (the total of the array):

print("x3 ndim: ",x3.ndim )
print("x3 shape", x3.shape)
print("x3 size ", x3.size)

#another useful attributes is the dtype
print("dtype:", x3.dtype)


#other attribute include itemsize, which lists the size (in bytes ) of each array
#element, and nbytes, which lists the total size (in bytes ) of the array:

print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

#Array Indexing : Accessing Single Elements
x1 = np.array([5,0,3, 4, 7, 9])
x1[0]
x1[4]

#to index from the end you can use negative index
x1[-1]
x1[-2]

#in a multimodal array you access items using a comma seperated tuple of indices
x2 = np.array([
    [3, 5, 2, 4],
    [7, 6, 8, 8],
    [1, 6, 7, 7]
    ])
x2[0, 0]
x2[2, 0]
x2[2, -1]

#you can also modify values using any of the abaove index notation:
x2[0, 0] = 12

#we also use the square brackets to access sub array by using colon between
#indices instaed of a comma
#x[start:stop:step], if any of these are unspecified, they are default to
#values start=0, stop=size of dimension, step =1.

#One dimensional subbarrays
x =np.arange(10)
x[:5] #first five elements
x[5:] #elements after index 5
x[4:7] #middle subarray
x[::2] #every element with step 2
x[1::2] # every other element starting at index 1

#when the step is negative
#the value for start and stop are swapped and this a very good way
#to reverse an array
x[::-1] #every element reversed
x[5::-2] #reversed every other from index 5

#Multi dimensional subarrays
#multidimensional slices works in thesame way ,
#with multiple slices seperated by comma
x2[:2, :3]
x2[:3, ::2] #all rows and  every other columns

#finally, subarray dimensions can even be reversed together:
x2[::-1, ::-1]

#accessing rows and columns
#you can do this by combining index and slicing, using an empty slice marked
#by a single colon(:)

print(x2[:, 0]) #first column of x2
print(x2[0, : ]) #first row of x2

#in the case of row access, the empty slice can be ommited for a compact syntax:
print(x2[0]) #equivalent to x[0, :]


#Subarray as no-copy views:

#array slices return viewa rather than copies of the array data
#code explanation belows
print(x2)
x2_sub = x2[:2, :2]
print(x2_sub)
#if we modify this array, it will change the original array too
x2_sub [0, 0] = 99
print(x2_sub)
print(x2)

#this behaviour is useful because when we work with large d
#datasets, we can access and process pieces of these datasets
#without the nbeed to copy the underlying data buffer.

#creating copies of arrays
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)
#If we now modify this subarray, the original array is not touched
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

#Reshaping of Arrays
#the most flexible way of doing this is with the
#reshape() method
#for example if you want to put the number 1 through 9 in a 3 x 3 grid
#you can do the following
grid = np.arange(1, 10).reshape((3,3))
print(grid)
#for this to work, the size of the initial array
#must match the size of the resized array

#another common reshaping pattern is the conversion of a one dimensional array
#into a two-dimensional row or column matrix.
#You can do this with the reshape method, or more easily by making
#use of the newaxis keyword within a slice operation

x = np.array([1, 2, 3])
#row vector via reshape
x.reshape((1, 3))

#row vector via newaxis
x[np.newaxis, :]

#column vector via reshape
x.reshape((3, 1))

#Column vector via newaxis
x[:, np.newaxis]

#Array Concatenation
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

#you can also concatenate more than two arrays at once
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

#np.concatenate can also be used for two dimensional arryas
grid = np.array([
    [1, 2, 3],
    [5, 6, 7]
])
np.concatenate([grid, grid])

#concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

#for working with array of mixed dimensions, it can be
#clearer to use the np.vstack (vertical stack) and
#np.hstack(horizontal stack) functions

x= np.array([1,2,3])
grid = np.array([
    [9, 8, 7],
    [6, 5, 4]
])

#vertically stack the arrays
np.vstack([x, grid])

#horizontally stack the arrays
y = np.array([[99], [99]])
np.hstack([grid, y])

#similarly np.dstack will stack the arrays along the third axis
z = np.array([[99, 99, 99], [99, 99, 99]])  # Shape (2, 3)
np.dstack([grid, z])

#splitting of arrays
#the opposite of concatenation
#which is implemented  by the functions np.split, np.hsplit,
#np.vsplit For each of these, we can pass a list of indices giving the
#split points
x = [1, 2, 3, 99, 99, 3, 2, 1 ]
x, x2, x3 = np.split(x, [3,  5])
print(x1, x2, x3)

#Notice that N split points lead to N + 1 subbarray
#The related functions np.hsplit and np.vsplit are similar
grid = np.arange(16).reshape((4,4))
grid
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

left, right = np.hsplit(grid, [2])
print(left)
print(right)
#similarly, np.dsplit will split arrays along the third axis
# Stack along the third axis
combined = np.dstack([grid, z])  # Shape (2, 3, 2)
split = np.dsplit(combined, 2)
print(split)


x3 ndim:  3
x3 shape (3, 4, 5)
x3 size  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes
[12  7  1]
[12  5  2  4]
[12  5  2  4]
[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[12  5]
 [ 7  6]]
[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[[99  5]
 [ 7  6]]
[[42  5]
 [ 7  6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1  2  3  3  2  1 99 99 99]
[5 0 3 4 7 9] [99 99] [3 2 1]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2